//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildersExchangeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILTER()
        {
            this.LINKs = new HashSet<LINK>();
        }
    
        public int FILTER_ID { get; set; }
        public string FILTER_NAME { get; set; }
        public string FILTER_OBJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK> LINKs { get; set; }
    }
}
