//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildersExchangeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKDATA
    {
        public int STATIC_LINK_ID { get; set; }
        public string LINKMD5 { get; set; }
        public Nullable<int> URL_ID { get; set; }
    
        public virtual LINK LINK { get; set; }
    }
}
